/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  // Based on Conventional Commits
  extends: ['@commitlint/config-conventional'],

  // Ignore messages generated by bots (adjust according to your workflow)
  ignores: [
    (m) => /^LD-\d+: .+/.test(m),
    (m) => m.startsWith('chore(master): release'),
    (m) => m.startsWith('chore: back-merge'),
    (m) => m.startsWith('Merge branch'),
    (m) => m.startsWith('Merge pull request'),
  ],

  // Custom rules
  rules: {
    // Allowed types (adjust to your reality)
    'type-enum': [
      2,
      'always',
      [
        'feat',      // new feature
        'fix',       // bug fix
        'perf',      // performance improvement
        'improve',   // code improvement
        'refactor',  // refactoring without behavior change
        'docs',      // documentation
        'test',      // tests
        'build',     // build system, deps
        'ci',        // CI configurations
        'chore',     // miscellaneous tasks
        'revert'     // reverts
      ],
    ],

    // Optional scopes (examples) — adjust or remove the rule if you don't want to enforce
    'scope-enum': [
      1,
      'always',
      [
        'api',
        'tests',
        'db',
        'ci',
        'deps',
        'partner',
        'logistic',
        'webhook',
        'marketplace',
        'communication',
        'pdv',
        'notification',
        'merchant',
        'user',
        'order',
        'financial',
        'backoffice',
        'core',
      ],
    ],

    // Require scope or not (0=off, 1=warn, 2=error)
    'scope-empty': [0, 'never'],

    // Subject line length
    'header-max-length': [2, 'always', 100],

    // Subject formatting
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],

    // Do not allow period at the end of subject
    'subject-full-stop': [2, 'never', '.'],

    // Messages without breaking changes should not use "!" in type
    'type-case': [2, 'always', 'lower-case'],
  },

  // Custom prompt configs
  prompt: {
    messages: {},
    questions: {
      type: {
        description: "please input type:",
      },
    },
  }
}
