version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:80'
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=http://localhost:3001/v1/auth/spotify/callback
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001